## Generate the LaTeX tables used in the manuscript appendix.
## Run this script from the project root.

mse_path <- "simulations/k_sensitivity/combined/mse_summary_all_K.csv"
beta_path <- "simulations/k_sensitivity/combined/beta_summary_all_K.csv"
coverage_path <- "simulations/k_sensitivity/combined/coverage_summary_all_K.csv"
output_path <- "paper/k_sensitivity_appendix.tex"

for (path in c(mse_path, beta_path, coverage_path)) {
  if (!file.exists(path)) {
    stop("Missing input file: ", path)
  }
}

mse <- read.csv(mse_path, check.names = FALSE)
beta <- read.csv(beta_path, check.names = FALSE)
coverage <- read.csv(coverage_path, check.names = FALSE)

config_order <- c("n=200, T=4", "n=200, T=8", "n=500, T=4")
k_order <- c(10, 20, 40)
method_order_mse <- c("mgcv::bam FD", "mgcv::bam FE", "mgcv::bam RE")
method_order_inference <- c("bam_fd", "bam_fe", "bam_re")
dgp_order <- c("linear", "quadratic", "sin_2pi")

method_label <- function(x) {
  switch(x,
    "mgcv::bam FD" = "\\code{bam} FD",
    "mgcv::bam FE" = "\\code{bam} FE",
    "mgcv::bam RE" = "\\code{bam} RE",
    "bam_fd" = "\\code{bam} FD",
    "bam_fe" = "\\code{bam} FE",
    "bam_re" = "\\code{bam} RE",
    stop("Unknown method: ", x)
  )
}

dgp_label <- function(x) {
  switch(x,
    "linear" = "linear",
    "quadratic" = "quadratic",
    "sin_2pi" = "$\\sin(2\\pi x)$",
    stop("Unknown DGP: ", x)
  )
}

panel_label <- function(configuration) {
  parts <- strsplit(configuration, ", ", fixed = TRUE)[[1]]
  paste0("$", parts[1], "$, $", parts[2], "$")
}

format_bind <- function(row) {
  sprintf("%.3f/%.3f", row$fraction_binding_90, row$fraction_binding_95)
}

format_edf <- function(row) {
  sprintf("%.2f/%.0f", row$mean_edf, row$mean_edf_ceiling)
}

one_row <- function(data, ...) {
  answer <- subset(data, ...)
  if (nrow(answer) != 1L) {
    stop("Expected one row but found ", nrow(answer))
  }
  answer
}

lines <- c(
  "% This file is generated by simulations/k_sensitivity/generate_appendix_tables.R.",
  "% Do not edit it by hand; edit the generator or the source summaries instead.",
  ""
)

add <- function(...) {
  lines <<- c(lines, ...)
}

## Estimation RMSE and EDF diagnostics.
add(
  "\\begin{landscape}",
  "\\scriptsize",
  "\\setlength{\\tabcolsep}{2.5pt}",
  "\\renewcommand{\\arraystretch}{0.93}",
  "\\begin{longtable}{llrrrrrrrrr}",
  "\\caption{Sensitivity of function estimation to the basis dimension}\\label{tab:k_sensitivity_rmse}\\\\",
  "\\toprule",
  "& & \\multicolumn{3}{c}{$K=10$} & \\multicolumn{3}{c}{$K=20$} & \\multicolumn{3}{c}{$K=40$} \\\\",
  "\\cmidrule(lr){3-5} \\cmidrule(lr){6-8} \\cmidrule(lr){9-11}",
  "DGP & Method & RMSE & EDF/ceiling & Bind & RMSE & EDF/ceiling & Bind & RMSE & EDF/ceiling & Bind \\\\",
  "\\midrule",
  "\\endfirsthead",
  "\\multicolumn{11}{c}{\\tablename~\\thetable{} (continued)} \\\\",
  "\\toprule",
  "& & \\multicolumn{3}{c}{$K=10$} & \\multicolumn{3}{c}{$K=20$} & \\multicolumn{3}{c}{$K=40$} \\\\",
  "\\cmidrule(lr){3-5} \\cmidrule(lr){6-8} \\cmidrule(lr){9-11}",
  "DGP & Method & RMSE & EDF/ceiling & Bind & RMSE & EDF/ceiling & Bind & RMSE & EDF/ceiling & Bind \\\\",
  "\\midrule",
  "\\endhead",
  "\\midrule",
  "\\multicolumn{11}{r}{Continued on next page} \\\\",
  "\\endfoot",
  "\\bottomrule",
  "\\endlastfoot"
)

for (configuration in config_order) {
  if (configuration == "n=500, T=4") add("\\pagebreak[4]")
  add(paste0("\\multicolumn{11}{l}{\\textit{Panel: ", panel_label(configuration), "}} \\\\"))
  add("\\midrule")
  for (dgp in dgp_order) {
    for (method in method_order_mse) {
      values <- character()
      for (k in k_order) {
        row <- mse[
          mse$configuration == configuration & mse$dgp == dgp &
            mse$method == method & mse$K_smooth == k,
          , drop = FALSE
        ]
        if (nrow(row) != 1L) stop("Nonunique MSE row")
        values <- c(
          values,
          sprintf("%.3f", row$rmse_times_100),
          format_edf(row),
          format_bind(row)
        )
      }
      add(paste0(
        dgp_label(dgp), " & ", method_label(method), " & ",
        paste(values, collapse = " & "), " \\\\"
      ))
    }
    if (dgp != tail(dgp_order, 1L)) add("\\addlinespace[2pt]")
  }
  if (configuration != tail(config_order, 1L)) add("\\midrule")
}

add(
  "\\end{longtable}",
  "{\\scriptsize\\noindent \\tablenote\\ RMSE entries report $100$ times the root mean squared error. EDF/ceiling reports the mean fitted effective degrees of freedom and its attainable ceiling. Bind reports, respectively, the fractions of Monte Carlo draws in which EDF is at least 90\\% and 95\\% of that ceiling. The ceiling is $K-1$ for the centered levels smooths used by FE and RE and $K$ for the first-difference linear-functional smooth.\\par}",
  "\\end{landscape}",
  ""
)

## Rejection frequencies for beta.
add(
  "\\begin{table}[H]",
  "\\centering",
  "\\footnotesize",
  "\\setlength{\\tabcolsep}{5pt}",
  "\\caption{Sensitivity of inference on $\\beta$ to the basis dimension}",
  "\\label{tab:k_sensitivity_beta}",
  "\\begin{tabular}{lrrrrrr}",
  "\\toprule",
  "& \\multicolumn{3}{c}{Size} & \\multicolumn{3}{c}{Power} \\\\",
  "\\cmidrule(lr){2-4} \\cmidrule(lr){5-7}",
  "Method & $K=10$ & $K=20$ & $K=40$ & $K=10$ & $K=20$ & $K=40$ \\\\",
  "\\midrule"
)

for (configuration in config_order) {
  add(paste0("\\multicolumn{7}{l}{\\textit{Panel: ", panel_label(configuration), "}} \\\\"))
  add("\\midrule")
  for (method in method_order_inference) {
    size <- numeric()
    power <- numeric()
    for (k in k_order) {
      size_row <- beta[
        beta$configuration == configuration & beta$method == method &
          beta$K_smooth == k & abs(beta$beta_true - 1) < 1e-10,
        , drop = FALSE
      ]
      power_row <- beta[
        beta$configuration == configuration & beta$method == method &
          beta$K_smooth == k & abs(beta$beta_true - 1.075) < 1e-10,
        , drop = FALSE
      ]
      if (nrow(size_row) != 1L || nrow(power_row) != 1L) stop("Nonunique beta row")
      size <- c(size, size_row$rejection_penalty_cluster)
      power <- c(power, power_row$rejection_penalty_cluster)
    }
    add(paste0(
      method_label(method), " & ",
      paste(sprintf("%.3f", c(size, power)), collapse = " & "), " \\\\"
    ))
  }
  if (configuration != tail(config_order, 1L)) add("\\midrule")
}

add(
  "\\bottomrule",
  "\\end{tabular}",
  "\\begin{minipage}{0.92\\textwidth}",
  "\\footnotesize \\tablenote\\ Entries report rejection frequencies based on the penalty-adjusted cluster sandwich. Size uses $\\beta=1$ and tests $H_0:\\beta=1$. Power uses $\\beta=1.075$ and tests the same null.",
  "\\end{minipage}",
  "\\end{table}",
  ""
)

## Coverage rates.
add(
  "\\begin{landscape}",
  "\\scriptsize",
  "\\setlength{\\tabcolsep}{2.5pt}",
  "\\renewcommand{\\arraystretch}{0.95}",
  "\\begin{longtable}{llrrrrrrrrr}",
  "\\caption{Sensitivity of coverage for centered $g$ to the basis dimension}\\label{tab:k_sensitivity_coverage}\\\\",
  "\\toprule",
  "& & \\multicolumn{3}{c}{$K=10$} & \\multicolumn{3}{c}{$K=20$} & \\multicolumn{3}{c}{$K=40$} \\\\",
  "\\cmidrule(lr){3-5} \\cmidrule(lr){6-8} \\cmidrule(lr){9-11}",
  "Model & Method & Avg. point & Min. point & Uniform & Avg. point & Min. point & Uniform & Avg. point & Min. point & Uniform \\\\",
  "\\midrule",
  "\\endfirsthead",
  "\\multicolumn{11}{c}{\\tablename~\\thetable{} (continued)} \\\\",
  "\\toprule",
  "& & \\multicolumn{3}{c}{$K=10$} & \\multicolumn{3}{c}{$K=20$} & \\multicolumn{3}{c}{$K=40$} \\\\",
  "\\cmidrule(lr){3-5} \\cmidrule(lr){6-8} \\cmidrule(lr){9-11}",
  "Model & Method & Avg. point & Min. point & Uniform & Avg. point & Min. point & Uniform & Avg. point & Min. point & Uniform \\\\",
  "\\midrule",
  "\\endhead",
  "\\midrule",
  "\\multicolumn{11}{r}{Continued on next page} \\\\",
  "\\endfoot",
  "\\bottomrule",
  "\\endlastfoot"
)

for (configuration in config_order) {
  add(paste0("\\multicolumn{11}{l}{\\textit{Panel: ", panel_label(configuration), "}} \\\\"))
  add("\\midrule")
  for (model in c("pl", "np")) {
    for (method in method_order_inference) {
      values <- numeric()
      for (k in k_order) {
        row <- coverage[
          coverage$configuration == configuration & coverage$model == model &
            coverage$method == method & coverage$se_type == "penalty" &
            coverage$K_smooth == k,
          , drop = FALSE
        ]
        if (nrow(row) != 1L) stop("Nonunique coverage row")
        values <- c(
          values,
          row$avg_pointwise_coverage,
          row$min_pointwise_coverage,
          row$uniform_coverage
        )
      }
      add(paste0(
        toupper(model), " & ", method_label(method), " & ",
        paste(sprintf("%.3f", values), collapse = " & "), " \\\\"
      ))
    }
    if (model == "pl") add("\\addlinespace[2pt]")
  }
  if (configuration != tail(config_order, 1L)) add("\\midrule")
}

add(
  "\\end{longtable}",
  "{\\scriptsize\\noindent \\tablenote\\ Entries report average pointwise, minimum pointwise, and uniform coverage for penalty-adjusted bands; PL and NP denote partially linear and nonparametric models.\\par}",
  "\\end{landscape}",
  ""
)

## EDF diagnostics for inference designs.
add(
  "\\begin{landscape}",
  "\\scriptsize",
  "\\setlength{\\tabcolsep}{4pt}",
  "\\renewcommand{\\arraystretch}{0.95}",
  "\\begin{longtable}{llrrrrrr}",
  "\\caption{EDF diagnostics for the inference sensitivity simulations}\\label{tab:k_sensitivity_inference_edf}\\\\",
  "\\toprule",
  "& & \\multicolumn{2}{c}{$K=10$} & \\multicolumn{2}{c}{$K=20$} & \\multicolumn{2}{c}{$K=40$} \\\\",
  "\\cmidrule(lr){3-4} \\cmidrule(lr){5-6} \\cmidrule(lr){7-8}",
  "Model & Method & EDF/ceiling & Bind & EDF/ceiling & Bind & EDF/ceiling & Bind \\\\",
  "\\midrule",
  "\\endfirsthead",
  "\\multicolumn{8}{c}{\\tablename~\\thetable{} (continued)} \\\\",
  "\\toprule",
  "& & \\multicolumn{2}{c}{$K=10$} & \\multicolumn{2}{c}{$K=20$} & \\multicolumn{2}{c}{$K=40$} \\\\",
  "\\cmidrule(lr){3-4} \\cmidrule(lr){5-6} \\cmidrule(lr){7-8}",
  "Model & Method & EDF/ceiling & Bind & EDF/ceiling & Bind & EDF/ceiling & Bind \\\\",
  "\\midrule",
  "\\endhead",
  "\\midrule",
  "\\multicolumn{8}{r}{Continued on next page} \\\\",
  "\\endfoot",
  "\\bottomrule",
  "\\endlastfoot"
)

for (configuration in config_order) {
  if (configuration == "n=500, T=4") add("\\pagebreak[4]")
  add(paste0("\\multicolumn{8}{l}{\\textit{Panel: ", panel_label(configuration), "}} \\\\"))
  add("\\midrule")
  for (model in c("beta", "pl", "np")) {
    for (method in method_order_inference) {
      values <- character()
      for (k in k_order) {
        if (model == "beta") {
          row <- beta[
            beta$configuration == configuration & beta$method == method &
              beta$K_smooth == k & abs(beta$beta_true - 1) < 1e-10,
            , drop = FALSE
          ]
        } else {
          row <- coverage[
            coverage$configuration == configuration & coverage$model == model &
              coverage$method == method & coverage$se_type == "penalty" &
              coverage$K_smooth == k,
            , drop = FALSE
          ]
        }
        if (nrow(row) != 1L) stop("Nonunique EDF row")
        values <- c(values, format_edf(row), format_bind(row))
      }
      model_name <- switch(model, beta = "$\\beta$", pl = "PL $g$", np = "NP $g$")
      add(paste0(
        model_name, " & ", method_label(method), " & ",
        paste(values, collapse = " & "), " \\\\"
      ))
    }
    if (model != "np") add("\\addlinespace[2pt]")
  }
  if (configuration != tail(config_order, 1L)) add("\\midrule")
}

add(
  "\\end{longtable}",
  "{\\scriptsize\\noindent \\tablenote\\ EDF/ceiling reports the mean fitted effective degrees of freedom and its attainable ceiling. Bind reports, respectively, the fractions of draws in which EDF is at least 90\\% and 95\\% of the ceiling. The $\\beta$ rows use the null design; its EDF diagnostics are numerically indistinguishable from those under the fixed alternative.\\par}",
  "\\end{landscape}",
  ""
)

writeLines(lines, output_path)
message("Wrote ", output_path)
